import type { CuratedGame, ProviderSearchOptions, SearchResult } from './types';

export async function searchBrowserGames(options: ProviderSearchOptions = {}): Promise<SearchResult> {
  // Jogos HTML5 gratuitos que podem ser embedados ou jogados diretamente
  const browserGames: CuratedGame[] = [
    {
      id: 'browser-1',
      title: '2048',
      description: 'Jogo de puzzle onde você junta números para chegar a 2048.',
      provider: 'browser',
      providerName: 'Browser Games',
      platform: ['Browser'],
      genre: ['Puzzle'],
      coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/2048_logo.svg/1200px-2048_logo.svg.png',
      rating: 4.3,
      playUrl: 'https://play2048.co/',
      tags: ['puzzle', 'math', 'casual'],
      isFree: true,
      isOpenSource: true,
      isAbandonware: false,
      isBrowserGame: true,
      developer: 'Gabriele Cirulli',
    },
    {
      id: 'browser-2',
      title: 'Agar.io',
      description: 'Controle uma célula e coma outras para crescer.',
      provider: 'browser',
      providerName: 'Browser Games',
      platform: ['Browser'],
      genre: ['Action'],
      coverUrl: 'https://upload.wikimedia.org/wikipedia/en/1/19/Agar.io_app_icon.png',
      rating: 4.0,
      playUrl: 'https://agar.io/',
      tags: ['multiplayer', 'action', 'casual'],
      isFree: true,
      isOpenSource: false,
      isAbandonware: false,
      isBrowserGame: true,
      developer: 'Matheus Valadares',
    },
    {
      id: 'browser-3',
      title: 'Slither.io',
      description: 'Coma pontos e outros jogadores para crescer sua cobra.',
      provider: 'browser',
      providerName: 'Browser Games',
      platform: ['Browser'],
      genre: ['Action'],
      coverUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8c/Slither.io_app_icon.png',
      rating: 4.1,
      playUrl: 'https://slither.io/',
      tags: ['multiplayer', 'action', 'casual'],
      isFree: true,
      isOpenSource: false,
      isAbandonware: false,
      isBrowserGame: true,
      developer: 'Steve Howse',
    },
    {
      id: 'browser-4',
      title: 'Krunker.io',
      description: 'FPS multiplayer rápido direto no navegador.',
      provider: 'browser',
      providerName: 'Browser Games',
      platform: ['Browser'],
      genre: ['FPS'],
      coverUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3e/Krunker.io_logo.png',
      rating: 4.2,
      playUrl: 'https://krunker.io/',
      tags: ['fps', 'multiplayer', 'shooter'],
      isFree: true,
      isOpenSource: false,
      isAbandonware: false,
      isBrowserGame: true,
      developer: 'Yendis Entertainment',
    },
    {
      id: 'browser-5',
      title: 'GeoGuessr',
      description: 'Descubra onde você está no mundo usando Google Street View.',
      provider: 'browser',
      providerName: 'Browser Games',
      platform: ['Browser'],
      genre: ['Puzzle'],
      coverUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/GeoGuessr_logo.png',
      rating: 4.5,
      playUrl: 'https://www.geoguessr.com/',
      tags: ['geography', 'puzzle', 'educational'],
      isFree: true,
      isOpenSource: false,
      isAbandonware: false,
      isBrowserGame: true,
      developer: 'GeoGuessr',
    },
    {
      id: 'browser-6',
      title: 'Little Alchemy 2',
      description: 'Combine elementos para descobrir novos itens.',
      provider: 'browser',
      providerName: 'Browser Games',
      platform: ['Browser'],
      genre: ['Puzzle'],
      coverUrl: 'https://littlealchemy2.com/static/img/little-alchemy-2.png',
      rating: 4.4,
      playUrl: 'https://littlealchemy2.com/',
      tags: ['puzzle', 'creative', 'casual'],
      isFree: true,
      isOpenSource: false,
      isAbandonware: false,
      isBrowserGame: true,
      developer: 'Recloak',
    },
    {
      id: 'browser-7',
      title: 'Tetris',
      description: 'O clássico jogo de quebra-cabeça com blocos.',
      provider: 'browser',
      providerName: 'Browser Games',
      platform: ['Browser'],
      genre: ['Puzzle'],
      coverUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7d/Tetris_NES_cover_art.jpg',
      rating: 4.8,
      playUrl: 'https://tetris.com/play-tetris',
      tags: ['puzzle', 'classic', 'arcade'],
      isFree: true,
      isOpenSource: false,
      isAbandonware: false,
      isBrowserGame: true,
      developer: 'Alexey Pajitnov',
    },
    {
      id: 'browser-8',
      title: 'Chess.com',
      description: 'Jogue xadrez online contra jogadores do mundo.',
      provider: 'browser',
      providerName: 'Browser Games',
      platform: ['Browser'],
      genre: ['Strategy'],
      coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/ChessSet.jpg/1200px-ChessSet.jpg',
      rating: 4.7,
      playUrl: 'https://www.chess.com/',
      tags: ['strategy', 'board', 'multiplayer'],
      isFree: true,
      isOpenSource: false,
      isAbandonware: false,
      isBrowserGame: true,
      developer: 'Chess.com',
    },
  ];

  let filtered = browserGames;
  if (options.query) {
    const q = options.query.toLowerCase();
    filtered = filtered.filter((g) =>
      g.title.toLowerCase().includes(q) ||
      g.description.toLowerCase().includes(q) ||
      g.tags.some((t) => t.toLowerCase().includes(q))
    );
  }

  return { games: filtered, total: filtered.length, provider: 'browser' };
}
